version: '3.8'

services:

  estoque-api:
    build:
      context: ./Estoque.API
    container_name: estoque-api
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

  faturamento-api:
    build:
      context: ./Faturamento.API
    container_name: faturamento-api
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - EstoqueServiceUrl=http://estoque-api:5001
    depends_on:
      - estoque-api

  frontend:
    build:
      context: ./frontend
    container_name: korp-frontend
    ports:
      - "4200:80"
    depends_on:
      - estoque-api
      - faturamento-api